### ISSUE TITLE
Searching Geographic resource error message received

### ISSUE THREAD

**Issue by fabioMoz** [FENIX-Platform/fenix-ui-catalog#8]
During verification of a geographic resource, once selected the resource type and selected geographic
I receive an error message using Chrome browser "The following pages have become unresponsive. You can wait for them to become responsive or kill them. Fenix metadata editor....and after around 3 minutes I receive the list of resources stored

**Comment by danielefenix** [comment]
@fabioMoz is this a bug to open on fenix-ui-dsd-editor? I suppose the problem is that it is not possible to load GAUL in one single request. Use dynamic load.
